#!/usr/bin/bash

#BSUB -W 3:00
#BSUB -n 4
#BSUB -M 16
#BSUB -R rusage[mem=16]
#BSUB -o /home/bnle/bsub_jobs/output/create_turef_from_genomename.%J.out
#BSUB -e /home/bnle/bsub_jobs/error/create_turef_from_genomename.%J.err
#BSUB -q e40short
#BSUB -J create_turef_from_3c_genomename
#BSUB -u bnle@mdanderson.org
#BSUB -B
#BSUB -N

source activate scPASU_env

# Variable
dir=dirpath
compartment=compartmentname
dir=${dir}${compartment}/
script_dir=scriptpath
script_dir=${script_dir}/3_peak_ref_cleanup/
GTF=gtfpath
outdir=${dir}/genomename_turef/

# Argument
flank=5000
final_annotation=gene_symbol

echo 'Assigning TU to peaks...'
Rscript ${script_dir}create_turef.R -d ${script_dir} -g ${GTF} -o ${outdir} -f $flank -a $gene_symbol
