#!/usr/bin/bash

#BSUB -W 3:00
#BSUB -n 16
#BSUB -M 64
#BSUB -R rusage[mem=64]
#BSUB -o /rsrch6/scratch/mol_cgenesis/bnle/bsub_jobs/output/runname_compartmentname_final_peaks_nuc_freq_plot_first.%J.out
#BSUB -e /rsrch6/scratch/mol_cgenesis/bnle/bsub_jobs/error/runname_compartmentname_final_peaks_nuc_freq_plot_first.%J.err
#BSUB -q short
#BSUB -J runname_compartmentname_final_peaks_nuc_freq_plot_first
#BSUB -u bnle@mdanderson.org
#BSUB -B
#BSUB -N

source activate scPASU_env

# Variable
dir=dirpath
compartment=compartmentname
dir=${dir}${compartment}/
script_dir=scriptpath
script_dir=${script_dir}/3_peak_ref_cleanup/
ref_genome=genomename

# Argument
PAS_filtering=false
kmer_to_plot=first
kmer_size=201
ncore=16

if [ $PAS_filtering == 'true' ]
   then file_prefix=${compartment}
else
   file_prefix=${compartment}_noPASfiltering
fi

outdir=${dir}3c_merged_prongs/nuc_freq_plot_${kmer_size}-mer/
ref=${dir}3c_merged_prongs/${file_prefix}_4thtu_assigned_peak_universe_updated.txt

echo Nuc frequency plotting...
Rscript ${script_dir}nuc_freq_plot.R -c ${ncore} -f ${file_prefix} -o $outdir -r $ref -k ${kmer_size} -b -n ${kmer_to_plot} -g $ref_genome

#### Plot polyAsite2.0 DB
#ref=${SCRATCH}/Ureter10_scPASU_run/atlas.clusters.2.0.GRCh38.96_minGapwidth1_peak_universe_updated.txt 
#Rscript ${script_dir}nuc_freq_plot.R -c ${ncore} -f atlas.clusters.2.0.GRCh38.96 -o $outdir -r $ref -k ${kmer_size} -n ${kmer_to_plot} -g $ref_genome
