#!/bin/sh

#BSUB -W 24:00
#BSUB -n 16
#BSUB -M 200
#BSUB -R rusage[mem=200]
#BSUB -o /rsrch6/scratch/mol_cgenesis/bnle/bsub_jobs/output/runname_compartmentname_4b_cellranger-peakcount_samplename.%J.out
#BSUB -e /rsrch6/scratch/mol_cgenesis/bnle/bsub_jobs/error/runname_compartmentname_4b_cellranger-peakcount_samplename.%J.err
#BSUB -q e40medium
#BSUB -J runname_compartmentname_4b_cellranger-peakcount_samplename
#BSUB -u bnle@mdanderson.org
#BSUB -B
#BSUB -N

# Variable
dir=dirpath
compartment=compartmentname
dir=${dir}${compartment}/
genome=genomename
sample=samplename
fastq_dir=${dir}4a_bam_to_fastq/${sample}/
sample_dir=$(ls $fastq_dir | grep $sample)
fastq_dir=${fastq_dir}${sample_dir} 
outdir=${dir}4b_cellranger_peakcount/
cellranger_dir=cellrangerpath

# Add tool paths to environmental path
export PATH=${cellranger_dir}:$PATH

mkdir -p ${outdir}
cd ${outdir}

# Argument
PAS_filtering=false
localcores=16
localmem=200

if [ $PAS_filtering == 'true' ]
   then fprefix=${compartment}
else
   fprefix=${compartment}_noPASfiltering
fi
genome=${genome}_${fprefix}
peak_refdir=${dir}${genome}

cellranger count --id $sample --fastqs=${fastq_dir} --sample=${sample} --localcores=${localcores} --localmem=${localmem} --transcriptome=${peak_refdir}
