#!/bin/sh

#BSUB -W 24:00
#BSUB -n 16
#BSUB -M 200
#BSUB -R rusage[mem=200]
#BSUB -o /rsrch6/scratch/mol_cgenesis/bnle/bsub_jobs/output/runname_compartmentname_4b_cellranger-genecount_samplename.%J.out
#BSUB -e /rsrch6/scratch/mol_cgenesis/bnle/bsub_jobs/error/runname_compartmentname_4b_cellranger-genecount_samplename.%J.err
#BSUB -q e40medium
#BSUB -J runname_compartment_4b_cellranger-genecount_samplename
#BSUB -u bnle@mdanderson.org
#BSUB -B
#BSUB -N

# Variable
dir=dirpath
compartment=compartmentname
dir=${dir}${compartment}/
sample=samplename
cellranger_refdir=cellrangerrefpath
fastq_dir=${dir}4a_bam_to_fastq/${sample}/
sample_dir=$(ls $fastq_dir | grep $sample)
fastq_dir=${fastq_dir}${sample_dir} 
outdir=${dir}4b_cellranger_genecount/
cellranger_dir=cellrangerpath

# Add tool paths to environmental path
export PATH=${cellranger_dir}:$PATH

mkdir -p ${outdir}
cd ${outdir}

# Argument
localcores=16
localmem=200

cellranger count --id $sample --fastqs=${fastq_dir} --sample=${sample} --localcores=${localcores} --localmem=${localmem} --transcriptome=${cellranger_refdir}
