#!/usr/bin/bash

#BSUB -W 24:00
#BSUB -n 16
#BSUB -M 64
#BSUB -R rusage[mem=64]
#BSUB -o /rsrch6/scratch/mol_cgenesis/bnle/bsub_jobs/output/runname_compartmentname_2c_split_peak_ref.%J.out
#BSUB -e /rsrch6/scratch/mol_cgenesis/bnle/bsub_jobs/error/runname_compartmentname_2c_split_peak_ref.%J.err
#BSUB -q medium
#BSUB -J runname_compartmentname_2c_split_peak_ref
#BSUB -u bnle@mdanderson.org
#BSUB -B
#BSUB -N

source activate scPASU_env

# Variable
dir=dirpath
compartment=compartmentname
dir=${dir}${compartment}/
file_prefix=${compartment}
script_dir=scriptpath
script_dir=${script_dir}/2_peak_ref/
chrs=chrsname
ucsc_utilities_dir=ucscutilitiespath

# Add tool paths to environmental path
export PATH=${ucsc_utilities_dir}:$PATH

# Argument
binsize=1
read_extsize=200
peak_extsize=100
ncores=16

echo Split multimodal peaks...

for prong in all_filtered_reads polyA_reads; do
    echo For ${prong} prong...
    fprefix=${file_prefix}_${prong}
    bw_dir=${dir}ucsc_tracks/bigwig_tracks/${binsize}bp/${prong}/
    summit_dir=${dir}2a_peaks/${prong}/
    bg_dir=${dir}2c_alignment_signals/${prong}/
    outdir=${dir}2d_split_peaks/${prong}/

    mkdir -p $bw_dir    
    mkdir -p $bg_dir

    if [ $prong == 'all_filtered_reads' ]; then
       export bam_dir=${dir}1e_merged_bam/
       export direction=3
    elif [ $prong == 'polyA_reads' ]; then
       export bam_dir=${dir}2b_polya/before_genomicAfiltering/bam_files/
       export direction=5
    fi
    
    echo Extract alignment signals...
    cd $bam_dir
    for strand in plus minus; do
       if [ $prong == 'all_filtered_reads' ]; then
          export bam_file=$(ls *genomicAfiltered*${strand}.bam)
       elif [ $prong == 'polyA_reads' ]; then
          export bam_file=$(ls *${strand}*nowrongstrand.bam)
       fi
       bamCoverage -b ${bam_file} -o ${bw_dir}${bam_file%.bam}_ext.bw -p $ncores -v --binSize $binsize --extendReads ${read_extsize}
       bigWigToBedGraph ${bw_dir}${bam_file%.bam}_ext.bw ${bg_dir}${bam_file%.bam}.bedGraph
       echo Also creating raw big Wig track for ${bam_dir}${bam_file} for track visualization...
       bamCoverage -b ${bam_file} -o ${bw_dir}${bam_file%.bam}_raw.bw -p $ncores -v --binSize $binsize
    done
    
    echo Process summit files...
    cd $summit_dir
    plus_summit=$(ls *plus*peaks.xls)
    grep -v '^#\|^[[:space:]]*$' ${plus_summit} > ${plus_summit%_peaks.xls}_peaks_summits.txt
    minus_summit=$(ls *minus*peaks.xls) 
    grep -v '^#\|^[[:space:]]*$' ${minus_summit} > ${minus_summit%_peaks.xls}_peaks_summits.txt 
    echo Extending MACS2 peaks by $extsize bp $direction prime then splitting them using gaps and summits...
    Rscript ${script_dir}2c_split_peaks.R -n $ncores -p $prong -b $bg_dir -s $summit_dir -f $fprefix -o $outdir -e ${direction},${peak_extsize} -c $chrs
done
