#!/usr/bin/bash

#BSUB -W 72:00
#BSUB -n 16
#BSUB -M 16
#BSUB -R rusage[mem=16]
#BSUB -o /rsrch6/scratch/mol_cgenesis/bnle/bsub_jobs/output/runname_compartmentname_2d_peak_ref_allchrs.%J.out
#BSUB -e /rsrch6/scratch/mol_cgenesis/bnle/bsub_jobs/error/runname_compartmentname_2d_peak_ref_allchrs.%J.err
#BSUB -q e40long
#BSUB -J runname_compartmentname_2d_peak_ref_allchrs
#BSUB -u bnle@mdanderson.org
#BSUB -B
#BSUB -N

source activate scPASU_env
module load bedtools/2.30.0

# Variable
dir=dirpath
compartment=compartmentname
dir=${dir}${compartment}/
script_dir=scriptpath
script_dir=${script_dir}/2_peak_ref/
chrs=chrsname

# Argument
all_filtered_reads_min_polya=3
polyA_reads_min_polya=1

for prong in all_filtered_reads polyA_reads; do
   echo For $prong prong...
   macs_dir=${dir}2d_split_peaks/${prong}/ 
   if [ $prong == 'all_filtered_reads' ]; then
      export polya_dir=${dir}2b_polya/after_genomicAfiltering/
      export min_polya=${all_filtered_reads_min_polya}
   elif [ $prong == 'polyA_reads' ]; then
      export polya_dir=${dir}2b_polya/before_genomicAfiltering/
      export min_polya=${polyA_reads_min_polya}
   fi
   outdir=${dir}2e_intersect_run/${prong}/
   if [ ! -d "$outdir" ]; then
      mkdir -p $outdir
   fi
   for strand in plus minus; do
      echo Retain peaks on ${strand} strand in ${chrs} with at least ${min_polya} polyA junction reads/sites...
      bash ${script_dir}2d_create_peak_ref.sh -m ${macs_dir} -p ${polya_dir} -o ${outdir} -s ${strand} -c ${chrs} -n ${min_polya} -t ${script_dir} &
   done
done
