#!/usr/bin/bash

#BSUB -W 24:00
#BSUB -n 32
#BSUB -M 200
#BSUB -R rusage[mem=200]
#BSUB -o /home/bnle/bsub_jobs/output/runname_1a_preprocess_bam_dedup_cleanup_samplename.%J.out
#BSUB -e /home/bnle/bsub_jobs/error/runname_1a_preprocess_bam_dedup_cleanup_samplename.%J.err
#BSUB -q e40medium
#BSUB -J runname_1a_preprocess_bam_dedup_cleanup_samplename
#BSUB -u bnle@mdanderson.org
#BSUB -B
#BSUB -N

source activate scPASU_env

# Variable
sample=samplename
cellranger_dir=cellrangeroutputpath
bam_file=${cellranger_dir}/${sample}/outs/possorted_genome_bam.bam
dir=dirpath
dedup_dir=${dir}/1a1_dedup_bam/
clean_bam_dir=${dir}/1a2_clean_bam/

mkdir -p ${dedup_dir} ${clean_bam_dir}

# Argument
NTHREADS=32

## 1. Dedup ##

echo 'Deduplicate reads...'
umi_tools dedup -I $bam_file -S ${dedup_dir}${sample}_dedup.bam --method=unique --extract-umi-method=tag --umi-tag=UB --cell-tag=CB
echo 'Indexing the last bam file...'
samtools index ${dedup_dir}${sample}_dedup.bam

## 2. Cleanup BAM - only uniquely mapped reads retained ##

echo 'Clean up bam...'
samtools view -b -q 1 ${dedup_dir}${sample}_dedup.bam > ${clean_bam_dir}${sample}_dedup_uniq.bam
echo 'Indexing the last bam file...'
samtools index ${clean_bam_dir}${sample}_dedup_uniq.bam
