#!/usr/bin/bash

#BSUB -W 24:00
#BSUB -n 16
#BSUB -M 20
#BSUB -R rusage[mem=20]
#BSUB -o /rsrch6/scratch/mol_cgenesis/bnle/bsub_jobs/output/runname_1c_subset_compartmentname_samplename.%J.out
#BSUB -e /rsrch6/scratch/mol_cgenesis/bnle/bsub_jobs/error/runname_1c_subset_compartmentname_samplename.%J.err
#BSUB -q medium
#BSUB -J runname_1c_subset_compartmentname_samplename
#BSUB -u bnle@mdanderson.org
#BSUB -B
#BSUB -N

source activate scPASU_env
subset=true
dir=dirpath
compartment=compartmentname
outdir=${dir}${compartment}/
sample=samplename
bam_dir_before_genomicAfiltered=${dir}1a2_clean_bam/
bam_dir_after_genomicAfiltered=${dir}1b_filtered_bam/
bam_output_before_genomicAfiltered=${sample}_dedup_uniq_${compartment}.bam
bam_output_after_genomicAfiltered=${sample}_dedup_uniq_filtered_${compartment}.bam
subset_dir=${outdir}1c_subset_bam/
subsetbam_dir=subsetbampath

## Subset ##
if [ ! -d "$subset_dir" ]; then
  mkdir -p $subset_dir
fi

if [ $subset == "true" ]; then
  # Variable
  barcode_file=${outdir}/barcode/${sample}_${compartment}_barcodes.tsv
  
  # Add tool paths to environmental path
  export PATH=${subsetbam_dir}:$PATH

  # Argument
  NTHREADS=32

  echo Subset-bam for the $compartment compartment before genomicA filtering...
  subset-bam -b ${bam_dir_before_genomicAfiltered}${sample}_dedup_uniq.bam -c ${barcode_file} -o ${subset_dir}${bam_output_before_genomicAfiltered} --log-level debug --cores $NTHREADS
  echo 'Indexing the last bam file...'
  samtools index ${subset_dir}${bam_output_before_genomicAfiltered}

  echo Subset-bam for the $compartment compartment after genomicA filtering...
  subset-bam -b ${bam_dir_after_genomicAfiltered}${sample}_dedup_uniq_filtered_2ndround.bam -c ${barcode_file} -o ${subset_dir}${bam_output_after_genomicAfiltered} ---log-level debug --cores $NTHREADS
  echo 'Indexing the last bam file...'
  samtools index ${subset_dir}${bam_output_after_genomicAfiltered}

else
  
