#!/usr/bin/bash

#BSUB -W 72:00
#BSUB -n 16
#BSUB -M 16
#BSUB -R rusage[mem=16]
#BSUB -o /rsrch6/scratch/mol_cgenesis/bnle/bsub_jobs/output/runname_compartmentname_merge_bam_aftergenomicAfiltering.%J.out
#BSUB -e /rsrch6/scratch/mol_cgenesis/bnle/bsub_jobs/error/runname_compartmentname_merge_bam_aftergenomicAfiltering.%J.err
#BSUB -q long
#BSUB -J runname_compartmentname_merge_bam_aftergenomicAfiltering
#BSUB -u bnle@mdanderson.org
#BSUB -B
#BSUB -N

source activate scPASU_env

# Variable
dir=dirpath
compartment=compartmentname
outdir=${dir}${compartment}/
bam_dir=${outdir}1d_subset_bam/
outdir=${outdir}1e_merged_bam/

if [ ! -d "$outdir" ]; then
  mkdir -p $outdir
fi

### Merge BAMs after genomicA filtering ###

cd ${bam_dir}
bam=$(ls --ignore='*.bai' | grep 'filtered')

## a. Merge  ##

cd ${bam_dir}

echo 'Merging the following bam files:' ${bam}
samtools merge ${outdir}dedup_uniq_genomicAfiltered_merged.bam ${bam}
echo 'Indexing the merged bam file...'
samtools index ${outdir}dedup_uniq_genomicAfiltered_merged.bam

## b. Split by strand ##

echo 'Splitting the plus bam file...'
samtools view -F 16 -b ${outdir}dedup_uniq_genomicAfiltered_merged.bam > ${outdir}dedup_uniq_genomicAfiltered_merged_plus.bam
echo 'Splitting the minus bam file...'
samtools view -f 16 -b ${outdir}dedup_uniq_genomicAfiltered_merged.bam > ${outdir}dedup_uniq_genomicAfiltered_merged_minus.bam

echo 'Indexing the plus bam file...'
samtools index ${outdir}dedup_uniq_genomicAfiltered_merged_plus.bam
echo 'Indexing the minus bam file...'
samtools index ${outdir}dedup_uniq_genomicAfiltered_merged_minus.bam
